<?php

namespace Disapamok\Modules;

class SriLanka{
	
	public static function getProvinces(){
        return array_keys(self::$SriLanka);
    }

    public static function getDiscricts($province){
        return array_keys(self::$SriLanka[$province]);
    }

    public static function getCities($district){
        foreach(self::$SriLanka as $province => $curDistrict){
            if(in_array($district,array_keys($curDistrict))){
                return $curDistrict[$district];
            }
        }
    }
	
    public static $SriLanka = array(
        'Eastern' => array(
            'Ampara' =>
            array(
                'Addalaichchenai',
                'Akkarepattu',
                'Alayadivembu',
                'Ampara',
                'Damana',
                'Dehiattakandiya',
                'Irakkamam',
                'Kalmunai',
                'Karaitivu',
                'Lahugala',
                'Maha Oya',
                'Navithanveli',
                'Nintavur',
                'Padiyathalawa',
                'Pottuvil',
                'Sainthamaruthu',
                'Sammanthurai',
                'Uhana',
            ),
            'Batticaloa' =>
            array(
                'Araiyampathy',
                'Batticaloa',
                'Chenkalady',
                'Eravur',
                'Kaluvanchikudy',
                'Kattankudy',
                'Kiran',
                'Kokkadichcholai',
                'Oddamavadi',
                'Pasikudah',
                'Vakarai',
                'Valaichchenai',
                'Vavunathivu',
                'Vellavely',
            ),
            'Trincomalee' =>
            array(
                'Gomarankadawala',
                'Kantalai',
                'Kinniya',
                'Kuchchaveli',
                'Morawewa',
                'Muttur',
                'Seruvila',
                'Siripura',
                'Thampalakamam',
                'Trincomalee',
                'Verugal',
            ),
        ),
        'North Central' =>
        array(
            'Anuradhapura' =>
            array(
                'Anuradhapura',
                'Bulnewa',
                'Eppawala',
                'Galenbindunuwewa',
                'Galnewa',
                'Ganewalpola',
                'Habarana',
                'Horowupotana',
                'Ipalogama',
                'Kahatagasdigiliya',
                'Kebithigollewa',
                'Kebitigollawa',
                'Kekirawa',
                'Konapathirawa',
                'Konwewa',
                'Madatugama',
                'Mahailuppallama',
                'Mahavilachchiya',
                'Maradankadawala',
                'Medawachchiya',
                'Mihintale',
                'Nochchiyagama',
                'Padaviya',
                'Palagala',
                'Palugaswewa',
                'Rajanganaya',
                'Rambewa',
                'Seeppukulama',
                'Talawa',
                'Tambuttegama',
                'Thambuttegama',
                'Thirappane',
                'Yakalla',
            ),
            'Polonnaruwa' =>
            array(
                'Aralaganwila',
                'Bakamuna',
                'Dimbulagala',
                'Elahera',
                'Galamuna',
                'Giritale',
                'Hingurakgoda',
                'Jayantipura',
                'Kaduruwela',
                'Lankapura',
                'Manampitiya',
                'Medirigiriya',
                'Minneriya',
                'Polonnaruwa',
                'Sungawila',
                'Welikanda',
            ),
        ),
        'Uva' =>
        array(
            'Badulla' =>
            array(
                'Badulla',
                'Bandarawela',
                'Beragala',
                'Diyatalawa',
                'Ella',
                'Haldummulla',
                'Hali Ela',
                'Haputale',
                'Kandaketiya',
                'Lunugala',
                'Mahiyanganaya',
                'Meegahakivula',
                'Passara',
                'tennapanguwa',
                'Uva-Paranagama',
                'Welimada',
                'Wiyaluwa',
            ),
            'Moneragala' =>
            array(
                'Badalkumbura',
                'Bibile',
                'Buttala',
                'Kataragama',
                'Madulla',
                'Medagama',
                'Moneragala',
                'Okkampitiya',
                'Sevanagala',
                'Siyambalanduwa',
                'Tanamalwila',
                'Wellawaya',
            ),
        ),
        'Western' =>
        array(
            'Colombo' =>
            array(
                'Angoda',
                'Athurugiriya',
                'Avissawella',
                'Battaramulla',
                'Boralesgamuwa',
                'Colombo 01',
                'Colombo 02',
                'Colombo 03',
                'Colombo 04',
                'Colombo 05',
                'Colombo 06',
                'Colombo 06',
                'Colombo 07',
                'Colombo 08',
                'Colombo 09',
                'Colombo 10',
                'Colombo 11',
                'Colombo 12',
                'Colombo 13',
                'Colombo 14',
                'Colombo 15',
                'Dehiwala',
                'Hanwella',
                'Homagama',
                'Kaduwela',
                'Kesbewa',
                'Kohuwala',
                'Kolonnawa',
                'Kosgama',
                'Kottawa',
                'Kotte',
                'Maharagama',
                'Malabe',
                'Mount Lavinia',
                'Nawala',
                'Nugegoda',
                'Paddukka',
                'Pannipitiya',
                'Piliyandala',
                'Rajagiriya',
                'Ranala',
                'Ratmalana',
                'Talawathugoda',
                'Wellampitiya',
            ),
            'Gampaha' =>
            array(
                'Attanagalla',
                'Biyagama',
                'Delgoda',
                'Divlapitiya',
                'Dompe',
                'Gampaha',
                'Ganemulla',
                'Ja-Ela',
                'Kadawatha',
                'Kandana',
                'Katana',
                'Katunayake',
                'Kelaniya',
                'Kiribathgoda',
                'Mahara',
                'Minuwangoda',
                'Mirigama',
                'Negombo',
                'Nittambuwa',
                'Ragama',
                'Veyangoda',
                'Wattala',
            ),
            'Kalutara' =>
            array(
                'Agalawatta',
                'Aluthgama',
                'Baduraliya',
                'Bandaragama',
                'Beruwala',
                'Bulathsinhala',
                'Dodangoda',
                'Horana',
                'Ingiriya',
                'Kalutara',
                'Madurawela',
                'Matugama',
                'Millaniya',
                'Panadura',
                'Wadduwa',
                'Walallavita',
            ),
        ),
        'Southern' =>
        array(
            'Galle' =>
            array(
                'Ahangama',
                'Ahungalla',
                'Ambalangoda',
                'Baddegama',
                'Balapitiya',
                'Batapola',
                'Bentota',
                'Boossa',
                'Elpitiya',
                'Galle',
                'Habaraduwa',
                'Hikkaduwa',
                'Hiniduma',
                'Imaduwa',
                'Karandeniya',
                'Karapitiya',
                'Koggala',
                'Kosgoda',
                'Mapalagama',
                'Nagoda',
                'Neluwa',
                'Pitigala',
                'Rathgama',
                'Thawalama',
                'Udugama',
                'Uragasmanhandiya',
                'Wanduramba',
                'Yakkalamulla',
            ),
            'Hambantota' =>
            array(
                'Ambalantota',
                'Angunukolapelessa',
                'Beliatta',
                'Hambantota',
                'Middeniya',
                'Tangalla',
                'Tissamaharama',
                'Walasmulla',
                'Weeraketiya',
            ),
            'Matara' =>
            array(
                'Athuraliya',
                'Akuressa',
                'Aparekka',
                'Denipitiya',
                'Deniyaya',
                'Devinuwara',
                'Dikwella',
                'Gandara',
                'Hakmana',
                'Kamburugamuwa',
                'Kamburupitiya',
                'Karaputugala',
                'Kekanadura',
                'Kirinda',
                'Kotapola',
                'Malimbada',
                'Matara',
                'Mirissa',
                'Morawaka',
                'Mulatiyana',
                'Pasgoda',
                'Pitabeddara',
                'Puhuwella',
                'Thelijjawila',
                'Thihagoda',
                'Tihagoda',
                'Weligama',
                'Welihinda',
                'Welipitiya',
            ),
        ),
        'Northern' =>
        array(
            'Jaffna' =>
            array(
                'Chankanai',
                'Chavakachcheri',
                'Jaffna',
                'Karainagar',
                'Karaveddy',
                'Kayts',
                'Kopay',
                'Maruthankerney',
                'Nallur',
                'Point Pedro',
                'Sandilipay',
                'Tellippalai',
                'Uduvil',
                'Velanai',
            ),
            'Kilinochchi' =>
            array(
                'Iranamadu',
                'Kandavalai',
                'Kilinochchi',
                'Pallai',
                'Paranthan',
                'Poonakary',
                'Velikkandal',
            ),
            'Mannar' =>
            array(
                'Adampan',
                'Chilawathurai',
                'Madhu',
                'Mannar',
                'Nanaddan',
            ),
            'Mullativu' =>
            array(
                'Ehatugaswewa',
                'Mullativu',
                'Oddusuddan',
                'Pandiyankulam',
                'Puthukkudiyiruppu',
                'Thunukkai',
            ),
            'Vavuniya' =>
            array(
                'Vavuniya',
                'Nedunkeni',
                'Cheddikulam',
            ),
        ),
        'Central' =>
        array(
            'Kandy' =>
            array(
                'Akurana',
                'Alawatugoda',
                'Ambatenna',
                'Ampitiya',
                'Daskara',
                'Daulagala',
                'Delthota',
                'Digana',
                'Galagedara',
                'Galhinna',
                'Gampola',
                'Gelioya',
                'Hanguranketa',
                'Hapugastalawa',
                'Harispattuwa',
                'Hatharaliyadda',
                'Kadugannawa',
                'Kadugannawa UC',
                'Kandy',
                'Katugastota',
                'Kundasale',
                'Madawala',
                'Madawala Bazaar',
                'Menikdiwela',
                'Minipe',
                'Nawalapitiya',
                'Pallekele',
                'Panvila',
                'Pathadumbara',
                'Pathahewaheta',
                'Peradeniya',
                'Pilimatalawa',
                'Poojapitiya',
                'Pussellawa',
                'Talatuoya',
                'Teldeniya',
                'Thumpane',
                'Udapalatha',
                'Ududumbara',
                'Udunuwara',
                'Ulapane',
                'Watadeniya',
                'Wattegama',
                'Welamboda',
                'Yatinuwara',
            ),
            'Matale' =>
            array(
                'Dambulla',
                'Elkaduwa',
                'Galewela',
                'Gammaduwa',
                'Inamaluwa',
                'Kaikawala',
                'Kibissa',
                'Laggala Pallegama',
                'Madawala Ulpotha',
                'Matale',
                'Nalanda',
                'Naula',
                'Palapathwela',
                'Pallepola',
                'Rattota',
                'Sigiriya',
                'Ukuwela',
                'Wahacotte',
                'Yatawatta',
            ),
            'Nuwara Eliya' =>
            array(
                'Agrapatana',
                'Ambewela',
                'Bogawantalawa',
                'Bopattalawa',
                'Dayagama',
                'Ginigathena',
                'Haggala',
                'Hapugastalawa',
                'Hatton',
                'Kotagala',
                'Kotmale',
                'Labukele',
                'Laxapana',
                'Madulla',
                'Maskeliya',
                'Nanuoya',
                'Nuwara Eliya',
                'Padiyapelella',
                'Ragala',
                'Ramboda',
                'Rozella',
                'Talawakele',
                'Udapussallawa',
                'Walapane',
                'Watawala',
            ),
        ),
        'Sabaragamuwa' =>
        array(
            'Kegalle' =>
            array(
                'Ambepussa',
                'Amitirigala',
                'Aranayaka',
                'Bulathkohupitiya',
                'Dehiovita',
                'Deraniyagala',
                'Galigamuwa',
                'Hemmathagama',
                'Karawanella',
                'Kegalle',
                'Kitulgala',
                'Kotiyakumbura',
                'Mawanella',
                'Rambukkana',
                'Ruwanwella',
                'Thalgaspitiya',
                'Warakapola',
                'Yatiyantota',
            ),
            'Ratnapura' =>
            array(
                'Ayagama',
                'Balangoda',
                'Eheliyagoda',
                'Elapatha',
                'Embilipitiya',
                'Godakawela',
                'Imbulpe',
                'Kahawatta',
                'Kalawana',
                'Kiriella',
                'Kolonne',
                'Kuruwita',
                'Nivitigala',
                'Opanayaka',
                'Panamure',
                'Pelmadulla',
                'Pelmadulla',
                'Pohorabawa',
                'Rakwana',
                'Ratnapura',
                'Weligepola',
            ),
        ),
        'North Western' =>
        array(
            'Kurunegala' =>
            array(
                'Alawwa',
                'Bingiriya',
                'Dambadeniya',
                'Dandagamuwa',
                'Galgamuwa',
                'Giriulla',
                'Hettipola',
                'Hiripitiya',
                'Ibbagamuwa',
                'Katupotha',
                'Kuliyapitiya',
                'Kurunegala',
                'Maho',
                'Mawathagama',
                'Melsiripura',
                'Narammala',
                'Nikaweratiya',
                'pahamune',
                'Panagamuwa',
                'Pannala',
                'Pannawa',
                'Polgahawela',
                'Potuhera',
                'Ridigama',
                'Wariyapola',
                'Wawathagama',
                'Yapahuwa',
            ),
            'Puttalam' =>
            array(
                'Anamaduwa',
                'Battuluoya',
                'Chilaw',
                'Dankotuwa',
                'Eluvankulam',
                'Kalpitiya',
                'Madampe',
                'Mahawewa',
                'Marawila',
                'Mundel',
                'Nattandiya',
                'Nuraicholai',
                'Palavi',
                'Puttalam',
                'Thillaiyadi',
                'Wennappuwa',
            ),
        ),
    );
}
